RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/100 [00:00<?, ?it/s]  1%|          | 1/100 [01:18<2:08:44, 78.02s/it]  2%|▏         | 2/100 [03:26<2:56:16, 107.92s/it] 19%|█▉        | 19/100 [03:33<10:00,  7.41s/it]   27%|██▋       | 27/100 [03:35<05:38,  4.64s/it] 66%|██████▌   | 66/100 [03:35<00:42,  1.26s/it] 82%|████████▏ | 82/100 [03:38<00:16,  1.07it/s] 96%|█████████▌| 96/100 [03:43<00:03,  1.27it/s]100%|██████████| 100/100 [03:43<00:00,  2.23s/it]
Exception ignored in: <function Pool.__del__ at 0x2aaea7560160>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
