RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/100 [00:00<?, ?it/s]  1%|          | 1/100 [50:24<83:11:02, 3024.88s/it]  3%|▎         | 3/100 [50:25<21:08:20, 784.55s/it]   9%|▉         | 9/100 [50:33<4:46:33, 188.94s/it]  15%|█▌        | 15/100 [50:40<2:09:10, 91.18s/it] 22%|██▏       | 22/100 [51:01<1:05:16, 50.22s/it] 32%|███▏      | 32/100 [51:14<29:55, 26.40s/it]   73%|███████▎  | 73/100 [54:50<04:50, 10.75s/it] 74%|███████▍  | 74/100 [54:53<04:34, 10.56s/it] 75%|███████▌  | 75/100 [54:53<04:15, 10.21s/it] 76%|███████▌  | 76/100 [54:58<03:58,  9.95s/it] 78%|███████▊  | 78/100 [55:30<03:53, 10.63s/it] 79%|███████▉  | 79/100 [55:30<03:27,  9.87s/it]100%|██████████| 100/100 [55:30<00:00, 33.31s/it]
Exception ignored in: <function Pool.__del__ at 0x2b930b153160>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
