RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/14 [00:00<?, ?it/s]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:36<04:12, 36.00s/it][A
 25%|██▌       | 2/8 [00:37<01:33, 15.56s/it][A100%|██████████| 8/8 [00:37<00:00,  4.66s/it]
  7%|▋         | 1/14 [00:43<09:22, 43.26s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:59<06:56, 59.46s/it][A
 25%|██▌       | 2/8 [01:00<02:30, 25.01s/it][A
 38%|███▊      | 3/8 [01:00<01:09, 13.86s/it][A
 62%|██████▎   | 5/8 [01:02<00:19,  6.35s/it][A
 75%|███████▌  | 6/8 [01:03<00:09,  4.88s/it][A
 88%|████████▊ | 7/8 [01:04<00:03,  3.77s/it][A100%|██████████| 8/8 [01:04<00:00,  8.06s/it]
 14%|█▍        | 2/14 [01:57<12:19, 61.63s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:42<11:56, 102.42s/it][A
100%|██████████| 8/8 [01:43<00:00,  9.43s/it] [A100%|██████████| 8/8 [01:43<00:00, 12.92s/it]
 21%|██▏       | 3/14 [03:45<15:08, 82.59s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [02:06<14:45, 126.55s/it][A
 38%|███▊      | 3/8 [02:08<02:48, 33.61s/it] [A100%|██████████| 8/8 [02:08<00:00, 16.09s/it]
 29%|██▊       | 4/14 [06:02<17:21, 104.19s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [02:37<18:19, 157.13s/it][A
 50%|█████     | 4/8 [02:39<02:01, 30.44s/it] [A100%|██████████| 8/8 [02:39<00:00, 19.97s/it]
 36%|███▌      | 5/14 [08:50<19:05, 127.23s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [02:58<20:49, 178.53s/it][A
 25%|██▌       | 2/8 [03:00<07:28, 74.70s/it] [A
 38%|███▊      | 3/8 [03:03<03:30, 42.11s/it][A
 62%|██████▎   | 5/8 [03:06<00:56, 18.97s/it][A
 75%|███████▌  | 6/8 [03:06<00:27, 13.64s/it][A100%|██████████| 8/8 [03:06<00:00, 23.35s/it]
 43%|████▎     | 6/14 [12:01<19:51, 148.92s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [03:33<24:51, 213.08s/it][A
 38%|███▊      | 3/8 [03:36<04:43, 56.64s/it] [A
100%|██████████| 8/8 [03:42<00:00, 16.37s/it][A100%|██████████| 8/8 [03:42<00:00, 27.82s/it]
 50%|█████     | 7/14 [15:47<20:18, 174.09s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [03:58<27:48, 238.40s/it][A
 50%|█████     | 4/8 [04:03<03:05, 46.37s/it] [A100%|██████████| 8/8 [04:03<00:00, 30.39s/it]
 57%|█████▋    | 8/14 [19:59<19:53, 198.94s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [04:31<31:39, 271.29s/it][A100%|██████████| 8/8 [04:31<00:00, 33.91s/it] 
 64%|██████▍   | 9/14 [24:34<18:33, 222.73s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [04:51<34:03, 291.88s/it][A
 75%|███████▌  | 6/8 [04:53<01:12, 36.07s/it] [A
 88%|████████▊ | 7/8 [05:00<00:30, 30.41s/it][A100%|██████████| 8/8 [05:01<00:00, 37.63s/it]
 71%|███████▏  | 10/14 [29:42<16:35, 248.94s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [05:40<39:41, 340.20s/it][A
100%|██████████| 8/8 [05:42<00:00, 31.18s/it] [A100%|██████████| 8/8 [05:42<00:00, 42.77s/it]
 79%|███████▊  | 11/14 [35:30<13:58, 279.42s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [05:46<40:28, 346.89s/it][A
 25%|██▌       | 2/8 [06:04<15:17, 152.95s/it][A100%|██████████| 8/8 [06:04<00:00, 45.51s/it] 
 86%|████████▌ | 12/14 [41:39<10:13, 306.57s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [06:21<44:27, 381.03s/it][A
 50%|█████     | 4/8 [06:21<04:48, 72.20s/it] [A
 75%|███████▌  | 6/8 [06:24<01:22, 41.35s/it][A100%|██████████| 8/8 [06:24<00:00, 48.03s/it]
 93%|█████████▎| 13/14 [48:11<05:32, 332.27s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [06:43<47:01, 403.08s/it][A100%|██████████| 8/8 [06:43<00:00, 50.38s/it] 
100%|██████████| 14/14 [54:59<00:00, 355.18s/it]100%|██████████| 14/14 [54:59<00:00, 235.66s/it]
Exception ignored in: <function Pool.__del__ at 0x2b0b6d0ba4c0>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
