RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/14 [00:00<?, ?it/s]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:09<01:03,  9.07s/it][A
 50%|█████     | 4/8 [00:09<00:06,  1.75s/it][A
 75%|███████▌  | 6/8 [00:10<00:02,  1.16s/it][A100%|██████████| 8/8 [00:10<00:00,  1.25s/it]
  7%|▋         | 1/14 [00:14<03:09, 14.59s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:08<00:59,  8.43s/it][A
 25%|██▌       | 2/8 [00:09<00:24,  4.10s/it][A100%|██████████| 8/8 [00:09<00:00,  1.19s/it]
 14%|█▍        | 2/14 [00:35<03:36, 18.07s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:08<01:02,  8.95s/it][A
 25%|██▌       | 2/8 [00:09<00:22,  3.75s/it][A
 50%|█████     | 4/8 [00:09<00:05,  1.45s/it][A100%|██████████| 8/8 [00:09<00:00,  1.15s/it]
 21%|██▏       | 3/14 [00:50<03:05, 16.83s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:08<01:02,  8.89s/it][A
 50%|█████     | 4/8 [00:09<00:07,  1.80s/it][A100%|██████████| 8/8 [00:09<00:00,  1.17s/it]
 29%|██▊       | 4/14 [01:02<02:29, 14.96s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:09<01:05,  9.32s/it][A
 38%|███▊      | 3/8 [00:09<00:12,  2.52s/it][A100%|██████████| 8/8 [00:09<00:00,  1.20s/it]
 36%|███▌      | 5/14 [01:14<02:05, 13.95s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:10<01:10, 10.08s/it][A
 62%|██████▎   | 5/8 [00:10<00:04,  1.63s/it][A100%|██████████| 8/8 [00:10<00:00,  1.34s/it]
 43%|████▎     | 6/14 [01:31<01:58, 14.81s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:09<01:05,  9.40s/it][A
 62%|██████▎   | 5/8 [00:09<00:04,  1.47s/it][A100%|██████████| 8/8 [00:09<00:00,  1.22s/it]
 50%|█████     | 7/14 [01:46<01:44, 14.95s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:10<01:13, 10.56s/it][A100%|██████████| 8/8 [00:10<00:00,  1.32s/it]
 57%|█████▋    | 8/14 [02:05<01:37, 16.19s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:10<01:10, 10.13s/it][A
 38%|███▊      | 3/8 [00:10<00:13,  2.79s/it][A
 88%|████████▊ | 7/8 [00:10<00:00,  1.08it/s][A100%|██████████| 8/8 [00:10<00:00,  1.34s/it]
 64%|██████▍   | 9/14 [02:19<01:17, 15.44s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:10<01:11, 10.14s/it][A100%|██████████| 8/8 [00:10<00:00,  1.27s/it]
 71%|███████▏  | 10/14 [02:37<01:05, 16.49s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:09<01:07,  9.71s/it][A
 38%|███▊      | 3/8 [00:09<00:13,  2.62s/it][A100%|██████████| 8/8 [00:09<00:00,  1.25s/it]
 79%|███████▊  | 11/14 [02:56<00:51, 17.27s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:09<01:08,  9.76s/it][A
 25%|██▌       | 2/8 [00:09<00:24,  4.08s/it][A
 50%|█████     | 4/8 [00:10<00:06,  1.75s/it][A100%|██████████| 8/8 [00:10<00:00,  1.32s/it]
 86%|████████▌ | 12/14 [03:10<00:32, 16.09s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:09<01:05,  9.38s/it][A
 25%|██▌       | 2/8 [00:09<00:24,  4.13s/it][A100%|██████████| 8/8 [00:09<00:00,  1.23s/it]
 93%|█████████▎| 13/14 [03:22<00:14, 14.84s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:09<01:06,  9.49s/it][A
 38%|███▊      | 3/8 [00:10<00:13,  2.76s/it][A100%|██████████| 8/8 [00:10<00:00,  1.29s/it]
100%|██████████| 14/14 [03:39<00:00, 15.61s/it]100%|██████████| 14/14 [03:39<00:00, 15.69s/it]
Exception ignored in: <function Pool.__del__ at 0x2b17d0cba4c0>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
