RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/1 [00:00<?, ?it/s]
  0%|          | 0/110 [00:00<?, ?it/s][A
  1%|          | 1/110 [18:21<33:21:47, 1101.90s/it][A
  2%|▏         | 2/110 [19:49<15:08:58, 504.99s/it] [A
  3%|▎         | 3/110 [21:03<9:09:54, 308.36s/it] [A
  5%|▍         | 5/110 [21:10<3:57:35, 135.76s/it][A
  7%|▋         | 8/110 [21:31<1:50:49, 65.20s/it] [A
 10%|█         | 11/110 [22:01<1:07:37, 40.98s/it][A
 18%|█▊        | 20/110 [22:17<23:02, 15.36s/it]  [A
 20%|██        | 22/110 [23:19<26:28, 18.05s/it][A
 29%|██▉       | 32/110 [24:10<14:12, 10.93s/it][A
 38%|███▊      | 42/110 [24:10<06:56,  6.13s/it][A
 38%|███▊      | 42/110 [24:22<06:56,  6.13s/it][A
 43%|████▎     | 47/110 [24:33<06:00,  5.72s/it][A
 65%|██████▍   | 71/110 [25:14<02:05,  3.23s/it][A
 66%|██████▋   | 73/110 [30:46<08:54, 14.44s/it][A
 69%|██████▉   | 76/110 [31:56<08:51, 15.62s/it][A
 72%|███████▏  | 79/110 [32:43<08:03, 15.61s/it][A
 78%|███████▊  | 86/110 [33:03<04:29, 11.24s/it][A
 84%|████████▎ | 92/110 [33:13<02:31,  8.42s/it][A
 89%|████████▉ | 98/110 [33:21<01:16,  6.36s/it][A
 97%|█████████▋| 107/110 [33:27<00:12,  4.14s/it][A100%|██████████| 110/110 [33:27<00:00, 18.25s/it]
100%|██████████| 1/1 [39:26<00:00, 2366.76s/it]100%|██████████| 1/1 [39:26<00:00, 2366.76s/it]
Exception ignored in: <function Pool.__del__ at 0x2ac36d0a14c0>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
