RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/14 [00:00<?, ?it/s]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:52<06:05, 52.25s/it][A
 25%|██▌       | 2/8 [00:56<02:24, 24.01s/it][A100%|██████████| 8/8 [00:56<00:00,  7.06s/it]
  7%|▋         | 1/14 [01:00<13:02, 60.22s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:10<08:16, 70.89s/it][A100%|██████████| 8/8 [01:10<00:00,  8.86s/it]
 14%|█▍        | 2/14 [02:13<13:37, 68.14s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:13<08:35, 73.58s/it][A
 62%|██████▎   | 5/8 [01:17<00:35, 11.79s/it][A100%|██████████| 8/8 [01:17<00:00,  9.69s/it]
 21%|██▏       | 3/14 [03:38<13:52, 75.67s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:21<09:30, 81.53s/it][A100%|██████████| 8/8 [01:21<00:00, 10.19s/it]
 29%|██▊       | 4/14 [05:04<13:16, 79.61s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:18<09:09, 78.51s/it][A
 25%|██▌       | 2/8 [01:19<03:18, 33.15s/it][A
 75%|███████▌  | 6/8 [01:20<00:15,  7.81s/it][A100%|██████████| 8/8 [01:20<00:00, 10.12s/it]
 36%|███▌      | 5/14 [06:29<12:15, 81.69s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:26<10:03, 86.26s/it][A
 50%|█████     | 4/8 [01:26<01:05, 16.45s/it][A100%|██████████| 8/8 [01:26<00:00, 10.84s/it]
 43%|████▎     | 6/14 [08:10<11:45, 88.13s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:26<10:04, 86.33s/it][A
 75%|███████▌  | 6/8 [01:26<00:21, 10.62s/it][A100%|██████████| 8/8 [01:29<00:00, 11.24s/it]
 50%|█████     | 7/14 [09:44<10:30, 90.02s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:25<10:01, 86.00s/it][A
 25%|██▌       | 2/8 [01:29<03:43, 37.22s/it][A
 50%|█████     | 4/8 [01:31<00:58, 14.64s/it][A100%|██████████| 8/8 [01:31<00:00, 11.44s/it]
 57%|█████▋    | 8/14 [11:22<09:15, 92.61s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:32<10:47, 92.48s/it][A100%|██████████| 8/8 [01:32<00:00, 11.56s/it]
 64%|██████▍   | 9/14 [13:06<08:00, 96.18s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:29<10:28, 89.83s/it][A
 25%|██▌       | 2/8 [01:36<04:05, 40.85s/it][A100%|██████████| 8/8 [01:36<00:00, 12.05s/it]
 71%|███████▏  | 10/14 [14:47<06:30, 97.63s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:35<11:09, 95.57s/it][A
 25%|██▌       | 2/8 [01:36<03:58, 39.79s/it][A
 38%|███▊      | 3/8 [01:38<01:54, 22.84s/it][A100%|██████████| 8/8 [01:38<00:00, 12.37s/it]
 79%|███████▊  | 11/14 [16:31<04:59, 99.69s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:37<11:19, 97.10s/it][A
 50%|█████     | 4/8 [01:38<01:14, 18.65s/it][A
 88%|████████▊ | 7/8 [01:42<00:09,  9.39s/it][A100%|██████████| 8/8 [01:42<00:00, 12.79s/it]
 86%|████████▌ | 12/14 [18:18<03:23, 101.97s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:40<11:45, 100.79s/it][A100%|██████████| 8/8 [01:40<00:00, 12.60s/it] 
 93%|█████████▎| 13/14 [20:05<01:43, 103.44s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:37<11:23, 97.64s/it][A
 38%|███▊      | 3/8 [01:39<02:09, 25.93s/it][A
 50%|█████     | 4/8 [01:47<01:19, 19.75s/it][A100%|██████████| 8/8 [01:47<00:00, 13.42s/it]
100%|██████████| 14/14 [21:59<00:00, 106.59s/it]100%|██████████| 14/14 [21:59<00:00, 94.24s/it] 
Exception ignored in: <function Pool.__del__ at 0x2b00422614c0>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
