RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/100 [00:00<?, ?it/s]  1%|          | 1/100 [12:18<20:18:22, 738.41s/it]  2%|▏         | 2/100 [12:45<8:42:18, 319.78s/it]   9%|▉         | 9/100 [13:48<1:22:06, 54.14s/it]  22%|██▏       | 22/100 [14:05<22:46, 17.52s/it]  43%|████▎     | 43/100 [14:21<06:50,  7.20s/it] 73%|███████▎  | 73/100 [17:06<02:48,  6.24s/it] 75%|███████▌  | 75/100 [17:58<03:01,  7.25s/it] 82%|████████▏ | 82/100 [18:14<01:52,  6.26s/it]100%|██████████| 100/100 [18:14<00:00, 10.95s/it]
Exception ignored in: <function Pool.__del__ at 0x2b5f179f4160>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
